### ISSUE TITLE
Consider interleaving data loading and computation

### ISSUE THREAD

**Issue by enchom** [JulietGroundwater/Groundwater#23]
Currently whenever a collection is plotted, all data files are loaded and then they are computed in batches. It might be more sensible to load a batch and compute a batch, interleaving the work.

The benefit of that is low memory usage at all times. If a very large collection is loaded, we are risking a potential crash.

The drawback is that it might require code refactoring and since it is not my code, I cannot be sure how difficult such change would be.

Feel free to close this issue without changing anything if you believe that it is not worth it.

**Comment by patricoferris** [comment]
Fixed in the `generateBurst` method called in the task
